# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# putting into commands
# https://circleci.com/docs/concepts/
  
commands:
  build_mavsdk:
    # working_directory: ~/git
    steps:
      - restore_cache:
          key: &mavsdk-cache mavsdk-cache-{{ .Environment.CACHE_VERSION }}-{{ .Environment.MACHINE_OS }}-{{ .Environment.MACHINE_ARCH }}-{{ .Environment.MAVSDK_COMMIT }}
      - run:
          name: Check if install already exist
          command: |
            DIR=~/git/MAVSDK/build/install
            if [[ -d "$DIR" ]]
            then
                echo "$DIR exists on your filesystem."
                circleci-agent step halt
            fi
      # - run:
      #     name: Install OpenCV Dependencies
      #     command: |
      #       sudo apt update
      #       sudo apt install -y libopencv-dev
      - run:
          name: Clone MAVSDK Repository
          command: |
            git clone https://github.com/vilota-dev/MAVSDK.git MAVSDK
      - run:
          name: Checkout Clean Commit
          command: |
            cd MAVSDK
            git checkout ${MAVSDK_COMMIT}
            git submodule update --init --recursive
      - run:
          name: Build MAVSDK
          command: |
            cd MAVSDK
            cmake -S. -Bbuild
            cmake --build build -j2
      - run:
          name: Install MAVSDK (Locally)
          command: |
            cd MAVSDK
            cmake --install build
      - save_cache:
          key: *mavsdk-cache
          paths:
            - ~/git/MAVSDK/build/install
  build_capnproto:
    steps:
      - restore_cache:
          key: &capnproto-cache capnproto-cache-{{ .Environment.CACHE_VERSION }}-{{ .Environment.MACHINE_OS }}-{{ .Environment.MACHINE_ARCH }}-{{ .Environment.CAPNPROTO_COMMIT }}
      - run:
          name: Check if capnproto already exist
          command: |
            DIR=~/git/capnproto
            if [[ -d "$DIR" ]]
            then
                echo "$DIR exists on your filesystem."
                circleci-agent step halt
            fi
      - run:
          name: Install Capnproto dependency
          command: |
            git clone https://github.com/capnproto/capnproto.git capnproto
            cd capnproto/c++
            git checkout ${CAPNPROTO_COMMIT}
            git submodule update --init --recursive
            autoreconf -i
            ./configure
            make -j2  # check # skip check for now
            sudo make install
      - save_cache:
          key: *capnproto-cache
          paths:
            - ~/git/capnproto
            
  build_ecal_mavlink_bridge:
    steps:
      - restore_cache:
          key: *mavsdk-cache
      - restore_cache:
          key: *capnproto-cache
      - run:
          name: Install Capnproto
          command: |
            cd capnproto/c++
            sudo make install
      - checkout:
          path: ecal_mavlink_bridge
      - run:
          name: ecal_mavlink_bridge submodule update
          command: |
            git -C ecal_mavlink_bridge submodule update --init --recursive
      - run:
          name: Install eCAL dependency
          command: |
            sudo add-apt-repository -y ppa:ecal/ecal-5.11
            sudo apt-get update
            sudo apt-get install ecal
      - run:
          name: Install spdlog / fmt dependency
          command: |
            sudo apt install libspdlog-dev libfmt-dev
      - run:
          name: Build ecal_mavlink_bridge (Release)
          command: |
            cd ecal_mavlink_bridge
            cmake -S. -Bbuild
            cmake --build build -j2
            cd build
            cpack
            mkdir artifacts
            cp *.deb artifacts
            cp *.tar.gz artifacts
      - run:
          name: Ldd command
          command: |
            cd ecal_mavlink_bridge/build
            ldd ecal_odometry_mavlink_bridge

      - store_artifacts:
          path: ~/git/ecal_mavlink_bridge/build/artifacts


executors:
  ubuntu2204-amd64: &ubuntu2204-amd64-executor
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    working_directory: ~/git
  ubuntu2204-arm64: &ubuntu2204-arm64-executor
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    working_directory: ~/git
  ubuntu2004-amd64: &ubuntu2004-amd64-executor
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    working_directory: ~/git
  ubuntu2004-arm64: &ubuntu2004-arm64-executor
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    working_directory: ~/git

workflows:
  ubuntu2204-amd64:
    jobs:
      - build-capnproto:
          os: ubuntu2204-amd64
          context: 
            - amd64
            - ubuntu2204
      - build-mavsdk:
          os: ubuntu2204-amd64
          context: 
            - amd64
            - ubuntu2204
      - build-ecal-mavlink-bridge:
          os: ubuntu2204-amd64
          context: 
            - amd64
            - ubuntu2204
          requires: 
            - build-capnproto
            - build-mavsdk
  ubuntu2204-arm64:
    jobs:
      - build-capnproto:
          os: ubuntu2204-arm64
          context: 
            - arm64
            - ubuntu2204
      - build-mavsdk:
          os: ubuntu2204-arm64
          context: 
            - arm64
            - ubuntu2204
      - build-ecal-mavlink-bridge:
          os: ubuntu2204-arm64
          context:             
            - arm64
            - ubuntu2204
          requires: 
            - build-capnproto
            - build-mavsdk
  ubuntu2004-amd64:
    jobs:
      - build-capnproto:
          os: ubuntu2004-amd64
          context: 
            - amd64
            - ubuntu2004
      - build-mavsdk:
          os: ubuntu2004-amd64
          context:
            - amd64
            - ubuntu2004
      - build-ecal-mavlink-bridge:
          os: ubuntu2004-amd64
          context:
            - amd64
            - ubuntu2004
          requires: 
            - build-capnproto
            - build-mavsdk
  ubuntu2004-arm64:
    jobs:
      - build-capnproto:
          os: ubuntu2004-arm64
          context: 
            - arm64
            - ubuntu2004
      - build-mavsdk:
          os: ubuntu2004-arm64
          context:
            - arm64
            - ubuntu2004
      - build-ecal-mavlink-bridge:
          os: ubuntu2004-arm64
          context:
            - arm64
            - ubuntu2004
          requires: 
            - build-capnproto
            - build-mavsdk

jobs:

  build-capnproto:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - build_capnproto
  build-mavsdk:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - build_mavsdk

  build-ecal-mavlink-bridge:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - build_ecal_mavlink_bridge

